name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - black
  - filelock
  - inflect
  - isort
  - matplotlib
  - mkdocs
  - pandas
  - parallel
  - pip
  - plotly
  - pip
  - pybtex
  - pylint
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata
  - pyyaml
  - pip:
    - linkchecker
    - mkdocs-material
    - mkdocs-gen-files
    - mkdocs-literate-nav
    - markdown-include
    - mdutils
    - mkdocs-section-index
    - mkdocs-macros-plugin
    - tabulate
    - datapackage
    - python-frontmatter
    - svgdigitizer >=0.2.0,<0.3.0
