name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - mkdocs
  - pip
  - pandas
  - matplotlib
  - plotly
  - pip:
    - mkdocs-material
    - mkdocs-gen-files
    - markdown-include
    - mdutils
    - mkdocs-section-index
    - mkdocs-macros-plugin
    - python-frontmatter
    - tabulate
    - datapackage
    - python-frontmatter
    # We should use a released version of svgdigitizer instead once
    # https://github.com/echemdb/svgdigitizer/issues/55 has been resolved.
    - git+git://github.com/saraedum/svgdigitizer.git@43f14e055fb75e4cd37af31a42295a5c9673d7fb
