name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - black
  - filelock
  - frictionless
  - inflect
  - jupyterlab
  - jupytext
  - make
  - matplotlib
  - mkdocs=1.2.3
  - myst-nb>=0.13.0,<0.14.0
  - myst-parser>=0.15,<0.17
  - pandas
  - pip
  - plotly
  - pip
  - pybtex
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata
  - pyyaml
  - sphinx>=4.3,<5
  - pip:
    - linkchecker
    - mkdocs-gen-files=0.3.4
    - mkdocs-literate-nav=0.4.1
    - mkdocs-macros-plugin=0.6.4
    - mkdocs-material=8.2.5
    - mkdocs-material-extension=1.0.3
    - mkdocs-section-index=0.3.3
    - markdown-include
    - mdutils
    - tabulate
    - datapackage
    - python-frontmatter
    - sphinx_rtd_theme>=1,<2
    - pymdown-extensions>=9.2,<10
    - svgdigitizer>=0.4.0,<0.5.0
