name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - mkdocs
  - pandas
  - matplotlib
  - plotly
  - pip
  - pip:
    - linkchecker
    - mkdocs-material
    - mkdocs-gen-files
    - markdown-include
    - mdutils
    - mkdocs-section-index
    - mkdocs-macros-plugin
    - python-frontmatter
    - tabulate
    - datapackage
    - python-frontmatter
    - mkdocs-literate-nav
