name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - inflect
  - matplotlib
  - mkdocs
  - pandas
  - parallel
  - pip
  - plotly
  - pip
  - pytest
  - pyyaml
  - pip:
    - linkchecker
    - mkdocs-material
    - mkdocs-gen-files
    - mkdocs-literate-nav
    - markdown-include
    - mdutils
    - mkdocs-section-index
    - mkdocs-macros-plugin
    - tabulate
    - datapackage
    - python-frontmatter
    - mkdocs-literate-nav
    # We should use a released version of svgdigitizer instead once
    # https://github.com/echemdb/svgdigitizer/issues/55 has been resolved.
    - git+https://github.com/echemdb/svgdigitizer.git
