name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - mkdocs
  - pip
  - pandas
  - matplotlib
  - pip:
    - mkdocs-material
    - markdown-include
    - mdutils
    - mkdocs-section-index
    - mkdocs-macros-plugin

