name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - black
  - filelock
  - frictionless
  - inflect
  - jupyterlab
  - jupytext
  - matplotlib
  - mkdocs
  - myst-nb>=0.13.0,<0.14.0
  - myst-parser>=0.15,<0.17
  - pandas
  - parallel
  - pip
  - plotly
  - pip
  - pybtex
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata
  - pyyaml
  - sphinx>=4.3,<5
  - pip:
    - linkchecker
    - mkdocs-material
    - mkdocs-gen-files
    - mkdocs-literate-nav
    - markdown-include
    - mdutils
    - mkdocs-section-index
    - mkdocs-macros-plugin
    - tabulate
    - datapackage
    - python-frontmatter
    - sphinx_rtd_theme>=1,<2
    - svgdigitizer >=0.3.0,<0.4.0
