site_name: echemdb.org
site_dir: generated/website
docs_dir: pages
theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: lime
  features:
  - navigation.tabs
  - navigation.indexes
  - navigation.tabs.sticky
  - toc.integrate

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - macros:
      modules:
      - echemdb.website.macros.legacy
  - gen-files:
      scripts:
      - echemdb/website/generator/__main__.py
  - section-index
  - literate-nav:
      nav_file: NAVIGATION.md

markdown_extensions:
  - extra
  - admonition
  - codehilite
  - smarty
  - meta
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown_include.include:
      base_path: pages
  - attr_list
  - pymdownx.arithmatex:
      generic: true
      inline_syntax:
        - dollar
      block_syntax:
        - dollar
        - begin
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - javascripts/tables.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
