name: Build
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  build-manual:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: digitize
        shell: bash -l {0}
        run: |
          pushd literature
          ls ./**/*.yaml | parallel --bar --halt now,fail=1 'svgdigitizer cv --sampling_interval .005 --package --metadata {} {.}.svg --outdir=../data/generated/svgdigitizer/{//}'
          popd
      - name: mkdocs
        shell: bash -l {0}
        run: |
          pip install -e .
          # Since no browser is installed during this CI run, plotly fails to
          # produce HTML output, see https://github.com/plotly/plotly.py/blob/2c2dd6ab2eeff73c782457f33c590c1d09a97625/packages/python/plotly/plotly/io/_renderers.py#L532
          export PLOTLY_RENDERER=browser
          mkdocs build
          mv data site
          # Disable further processing by GitHub
          touch site/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          TARGET_FOLDER: ""
        if: ${{ github.event_name == 'push' }}
