name: Build
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  build-manual:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: digitize
        shell: bash -l {0}
        run: |
          pushd literature
          ls ./**/*.yaml | parallel --bar --halt now,fail=1 'svgdigitizer cv --sampling_interval .005 --package --metadata {} {.}.svg --outdir=../data/generated/svgdigitizer/{//}'
          popd
      - name: mkdocs
        shell: bash -l {0}
        run: |
          pip install -e .
          mkdocs build
          mv data site
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          TARGET_FOLDER: ""
        if: ${{ github.event_name == 'push' }}
